backend/app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app,session,jsonify
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from ..models import User
from ..extensions import db, mail
from itsdangerous import URLSafeTimedSerializer
from flask_mail import Message
from ..forms import RequestResetForm
import smtplib
from datetime import datetime, timedelta
from flask_jwt_extended import (
    JWTManager, create_access_token, jwt_required, get_jwt_identity,create_access_token, set_access_cookies
)
from .api import token_or_login_required
import jwt

auth_bp = Blueprint('auth_bp', __name__)

@auth_bp.route('/', methods=['GET', 'POST'])
def auth_page():
    if request.method == 'POST':
        if 'login' in request.form:
            return login()
        elif 'signup' in request.form:
            return signup()
    return render_template('auth.html')


@auth_bp.route('/login', methods=['POST'])
def login():
    data = request.get_json() if request.is_json else request.form
    email = data.get('email')
    password = data.get('password')
    remember = True if data.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if user and check_password_hash(user.password, password):
        login_user(user, remember=remember)
        
        # Ensure the token is generated and saved
        token = generate_and_save_token(user)
        
        # Create a response object and set the token in the cookie
        response = redirect(url_for('profile_bp.profile'))
        response.set_cookie('api_token', token, httponly=True, secure=True,max_age=60*60*24*7)
        response.set_cookie('user_id', str(user.id), httponly=True, secure=True)
        response.set_cookie('email', email, httponly=True, secure=True)
        
        # If it's an API request, return the token in JSON format
        if request.is_json or request.path.startswith('/api/'):
            return jsonify({'api_token': token, 'user_id': user.id, 'email': email, 'msg': 'Successfully logged in!'})
        
        flash('Successfully logged in!', 'success')
        return response
    else:
        flash('Login failed. Check your email and password.', 'error')
        return redirect(url_for('auth_bp.auth_page'))
    
@auth_bp.route('/signup', methods=['POST'])
def signup():
    data = request.get_json() if request.is_json else request.form
    email = data.get('email')
    username = data.get('username')
    password = data.get('password')

    existing_user = User.query.filter_by(email=email).first()
    if existing_user:
        flash('Email already in use. Please choose a different email.', 'error')
        return redirect(url_for('auth_bp.auth_page'))

    if len(password) < 6:
        flash('Password must be at least 6 characters long.', 'error')
        return redirect(url_for('auth_bp.auth_page'))

    hashed_password = generate_password_hash(password, method='pbkdf2:sha256')
    new_user = User(email=email, username=username, password=hashed_password)
    db.session.add(new_user)
    db.session.commit()
    login_user(new_user)
    #token = generate_and_save_token(new_user)
    access_token = create_access_token(identity=new_user.id)
    new_user.api_token = access_token
    db.session.commit()
    
    response = redirect(url_for('profile_bp.profile'))
    response.set_cookie('api_token', access_token, httponly=True, secure=True)
    flash('Account created successfully!', 'success')
    return response


#Test Tokens
def generate_and_save_token(user):
    # Check if the current token is valid
    if user.api_token:
        try:
            data = jwt.decode(user.api_token, current_app.config['SECRET_KEY'], algorithms=['HS256'])
            if data['exp'] > datetime.utcnow().timestamp():
                return user.api_token
        except jwt.ExpiredSignatureError:
            pass  
        except jwt.InvalidTokenError:
            pass  
    
    # Generate a new token
    token_data = {
        'user_id': user.id,
        'sub': user.id,
        'exp': (datetime.utcnow() + timedelta(days=7)).timestamp()
    }
    token = create_access_token(identity=user.id, additional_claims=token_data)
    user.api_token = token
    db.session.commit()
    return token
    
@auth_bp.route('/logout')
@token_or_login_required
def logout():
    session.clear()
    response = redirect(url_for('auth_bp.auth_page'))
    response.delete_cookie('api_token', path='/', domain=None)
    response.delete_cookie('user_id', path='/', domain=None)
    response.delete_cookie('email', path='/', domain=None)
    logout_user()
    flash('You have been logged out.', 'success')
    return response


@auth_bp.route('/request_reset', methods=['GET', 'POST'])
def request_reset():
    if request.method == 'POST':
        email = request.form.get('email')
        user = User.get_user_by_email(email)
        if user:
            token = generate_reset_token(user.email)
            send_reset_email(user.email, token)
            flash('A password reset email has been sent.', 'info')
        else:
            flash('Email not found.', 'warning')
        return redirect(url_for('auth_bp.request_reset'))
    return render_template('request_reset.html')

def send_reset_email(to, token_id):
    msg = Message('Shlaiman Finder - Password Reset Request', sender=current_app.config['MAIL_DEFAULT_SENDER'], recipients=[to])
    msg.body = f'''To reset your password, visit the following link:
        {url_for('auth_bp.reset_password', token=token_id, _external=True)}
        If you did not make this request then simply ignore this email and no changes will be made.
        '''
    try:
        mail.send(msg)
        current_app.logger.info(f"Sent reset password to: {to}")
        return 'Email sent successfully!'
    except smtplib.SMTPException as e:
        current_app.logger.error(f"Failed to send email: {e}")
        return False


@auth_bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    email = verify_reset_token(token)
    if not email:
        flash('Invalid or expired token.', 'danger')
        return redirect(url_for('auth_bp.request_reset'))
    
    if request.method == 'POST':
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        if password != confirm_password:
            flash('Passwords do not match.', 'danger')
            return redirect(url_for('auth_bp.reset_password', token=token))
        user = User.query.filter_by(email=email).first()
        if user:
            user.password = generate_password_hash(password, method='pbkdf2:sha256')
            db.session.commit()
            flash('Your password has been updated!', 'success')
            return redirect(url_for('auth_bp.auth_page'))  
    
    return render_template('reset_password.html', token=token)

def generate_reset_token(email):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    return serializer.dumps(email, salt=current_app.config['SECURITY_PASSWORD_SALT'])

def verify_reset_token(token, expiration=3600):
    serializer = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    try:
        email = serializer.loads(
            token,
            salt=current_app.config['SECURITY_PASSWORD_SALT'],
            max_age=expiration
        )
    except:
        return None
    return email

@auth_bp.route('/test-email')
def test_email():
    msg = Message('Test Email', sender=current_app.config['MAIL_DEFAULT_SENDER'], recipients=['theshahnis@gmail.com'])
    msg.body = 'This is a test email sent from Flask-Mail with Postfix as the mail server.'
    try:
        mail.send(msg)
        return 'Email sent successfully!'
    except Exception as e:
        return f'Failed to send email: {e}'

backend/app/routes/location.py
from flask import Blueprint, render_template, jsonify, request, url_for, current_app
from flask_login import login_required, current_user
from ..models import Location, MeetingPoint, StaticLocation, User, Group, Hotel, UserHotel
from ..extensions import db
from datetime import datetime, timedelta
import pytz
import os
import secrets
from PIL import Image
from .api import token_or_login_required

location_bp = Blueprint('location_bp', __name__)

@location_bp.route('/test-location', methods=['GET'])
@token_or_login_required
def test_location():
    return render_template('test-location.html')


@location_bp.route('/update', methods=['POST'])
@token_or_login_required
def update_location():
    try:
        data = request.get_json()
        latitude = data.get('latitude')
        longitude = data.get('longitude')

        if latitude and longitude:
            location = Location.query.filter_by(user_id=current_user.id).order_by(Location.timestamp.desc()).first()
            if location:
                location.latitude = latitude
                location.longitude = longitude
                location.timestamp = datetime.now()
            else:
                location = Location(
                    user_id=current_user.id,
                    latitude=latitude,
                    longitude=longitude,
                    timestamp=datetime.now()
                )
                db.session.add(location)
            db.session.commit()
            return jsonify({'message': 'Location updated successfully'}), 200

        return jsonify({'message': 'Invalid data'}), 400
    except Exception as e:
        print(f"Error with updating location - {e}")
        return jsonify({'message': 'Internal Server Error'}), 500

@location_bp.route('/data', methods=['GET'])
@token_or_login_required
def get_location_data():
    location = Location.query.filter_by(user_id=current_user.id).order_by(Location.timestamp.desc()).first()
    if location:
        return jsonify({
            'latitude': location.latitude,
            'longitude': location.longitude,
            'timestamp': location.timestamp.isoformat()
        }), 200
    return jsonify({'message': 'No location data found'}), 404

@location_bp.route('/<int:user_id>', methods=['GET'])
@token_or_login_required
def get_user_location(user_id):
    location = Location.query.filter_by(user_id=user_id).order_by(Location.timestamp.desc()).first()
    if location:
        return jsonify({
            'latitude': location.latitude,
            'longitude': location.longitude,
            'timestamp': location.timestamp.isoformat()
        }), 200
    return jsonify({'message': 'No location data found'}), 404

@location_bp.route('/locations', methods=['GET'])
@token_or_login_required
def get_locations():
    if not current_user.group_id:
        return jsonify({'users': [], 'static_locations': [], 'meeting_points': []})

    def format_time(dt):
        return dt.strftime("%Y-%m-%d %H:%M:%S") if dt else None

    def calculate_remaining_time(created_at, duration):
        expires_at = created_at + timedelta(hours=duration)
        remaining = expires_at - datetime.now()
        return remaining if remaining.total_seconds() > 0 else timedelta(0)


    # Fetch user locations
    users = User.query.filter_by(group_id=current_user.group_id).all()
    user_locations = []
    for user in users:
        location = Location.query.filter_by(user_id=user.id).order_by(Location.timestamp.desc()).first()
        if location:
            user_locations.append({
                'username': user.username,
                'latitude': location.latitude,
                'longitude': location.longitude,
                'profile_image': url_for('static', filename='profile_pics/' + (user.profile_image if user.profile_image else 'default.png')),
                'note': user.note,
                'isMeetingPoint': False,
                'created_at': format_time(location.timestamp),
                'remaining_time': None,
                'user_id':user.id
            })

    # Fetch meeting points
    meeting_points = MeetingPoint.query.filter_by(group_id=current_user.group_id).all()
    meeting_point_locations = []
    for point in meeting_points:
        remaining_time = calculate_remaining_time(point.created_at, point.duration)
        if remaining_time.total_seconds() > 0:
            meeting_point_locations.append({
                'username': point.username,
                'latitude': point.latitude,
                'longitude': point.longitude,
                'profile_image': url_for('static', filename='meeting_pics/' + (point.image if point.image else 'default_meeting_point.png')),
                'note': point.note,
                'isMeetingPoint': True,
                'created_at': format_time(point.created_at),
                'remaining_time': str(remaining_time),
                'location_id':point.id
            })

    # Fetch static locations
    static_locations = StaticLocation.query.all()
    static_location_data = []
    for location in static_locations:
        static_location_data.append({
            'username': location.name,
            'latitude': location.latitude,
            'longitude': location.longitude,
            'profile_image': url_for('static', filename='static_pics/' + (location.image if location.image else 'static_location.jpg')),
            'note': location.note,
            'isMeetingPoint': False,
            'created_at': None,
            'remaining_time': None,
            'location_id':location.id
        })

    # Debug information
    print(f"Total user locations: {len(user_locations)}")
    print(f"Total meeting points: {len(meeting_point_locations)}")
    print(f"Total static locations: {len(static_location_data)}")

    return jsonify({
        'users': user_locations,
        'static_locations': static_location_data,
        'meeting_points': meeting_point_locations
    })

@location_bp.route('/create_location', methods=['POST'])
@token_or_login_required
def create_location():
    latitude = request.form.get('latitude')
    longitude = request.form.get('longitude')
    username = request.form.get('username')
    note = request.form.get('note')
    loc_type = request.form.get('locType')
    image = request.files.get('image')
    duration = request.form.get('duration') if loc_type == 'meetingPoint' else None

    # Logging received form data
    print(f"Received data: latitude={latitude}, longitude={longitude}, username={username}, note={note}, loc_type={loc_type}, image={image}, duration={duration}")

    if not (latitude and longitude and username and loc_type):
        return jsonify({'message': 'Invalid data'}), 400

    image_filename = None
    if image:
        target_dir = 'static/meeting_pics' if loc_type == 'meetingPoint' else 'static/static_pics'
        try:
            image_filename = save_picture(image, target_dir)
        except ValueError as e:
            return jsonify({'message': str(e)}), 400

    try:
        if loc_type == 'meetingPoint':
            meeting_point = MeetingPoint(
                latitude=latitude,
                longitude=longitude,
                username=username,
                note=note,
                image=image_filename,
                group_id=current_user.group_id,
                duration=int(duration)
            )
            db.session.add(meeting_point)
        else:
            static_location = StaticLocation(
                latitude=latitude,
                longitude=longitude,
                name=username,
                note=note,
                image=image_filename
            )
            db.session.add(static_location)

        db.session.commit()
        print("Location created successfully")
        return jsonify({'message': 'Location created successfully'}), 200
    except Exception as e:
        db.session.rollback()
        print(f"Error: {e}")
        return jsonify({'message': 'Failed to create location', 'error': str(e)}), 500

@location_bp.route('/delete_meeting_point', methods=['POST'])
@token_or_login_required
def delete_meeting_point(meeting_point_id):
    if not current_user.is_superuser:
        return jsonify({'message': 'Permission denied'}), 403

    meeting_point = MeetingPoint.query.get_or_404(meeting_point_id)
    db.session.delete(meeting_point)
    db.session.commit()
    return jsonify({'message': 'Meeting point deleted successfully'}), 200

@location_bp.route('/delete_static_location/<int:location_id>', methods=['POST'])
@token_or_login_required
def delete_static_location(location_id):
    if not current_user.is_superuser:
        return jsonify({'message': 'Permission denied'}), 403

    static_location = StaticLocation.query.get_or_404(location_id)
    db.session.delete(static_location)
    db.session.commit()
    return jsonify({'message': 'Static location deleted successfully'}), 200

@location_bp.route('/static_locations', methods=['GET'])
@token_or_login_required
def get_static_locations():
    static_locations = StaticLocation.query.all()
    locations = []
    for location in static_locations:
        locations.append({
            'id': location.id,
            'name': location.name,
            'latitude': location.latitude,
            'longitude': location.longitude,
            'note': location.note,
            'location_id':location.id,
            'image': url_for('static', filename='static/static_pics/' + (location.image if location.image else 'static_location.jpg'))
        })

    return jsonify({'locations': locations})

def save_picture(form_picture, target_dir):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)

backend/app/templates/auth.html
{% extends "base.html" %}

{% block title %}ShlaimanFinder - Login{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

{% endblock %}

{% block content %}
<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 id="loginTab" class="active" onclick="showLogin()"> Sign In </h2>
    <h2 id="signupTab" class="inactive underlineHover" onclick="showSignup()">Sign Up </h2>

    <!-- Icon -->
    <div class="fadeIn first">
      <img src="{{ url_for('static', filename='images/logo1.png') }}" id="icon" alt="User Icon" />
    </div>

    <!-- Login Form -->
    <div id="loginForm">
      <form method="POST" action="{{ url_for('auth_bp.auth_page') }}">
        <input type="hidden" name="login" value="login">
        <input type="email" id="loginEmail" class="fadeIn second" name="email" placeholder="email" required>
        <input type="password" id="loginPassword" class="fadeIn third" name="password" placeholder="password" required>

        <!-- Custom Checkbox -->
        <div class="checkbox-wrapper-5 fadeIn fourth">
          <label for="check-5">
            <input type="checkbox" id="check-5" name="remember">
            <span class="tick_mark"></span>
          </label>
          <span> Remember me?</span>
        </div>

        <input type="submit" class="fadeIn fifth" value="Log In">
      </form>

      <!-- Remind Password -->
      <div id="formFooter">
        <a class="underlineHover" href="{{ url_for('auth_bp.request_reset') }}">Forgot Password?</a>
      </div>
    </div>

    <!-- Signup Form -->
    <div id="signupForm" style="display: none;">
      <form method="POST" action="{{ url_for('auth_bp.auth_page') }}">
        <input type="hidden" name="signup" value="signup">
        <input type="text" id="signupUsername" class="fadeIn second" name="username" placeholder="username" required>
        <input type="email" id="signupEmail" class="fadeIn second" name="email" placeholder="email" required>
        <input type="password" id="signupPassword" class="fadeIn third" name="password" placeholder="password" required>
        <input type="submit" class="fadeIn fourth" value="Sign Up">
      </form>

      <!-- Redirect to Login -->
      <div id="formFooter">
        <a class="underlineHover" href="#" onclick="showLogin()">Already have an account? Sign In</a>
      </div>
    </div>
  </div>
</div>

<script>
  function showLogin() {
    document.getElementById('loginForm').style.display = 'block';
    document.getElementById('signupForm').style.display = 'none';
    document.getElementById('loginTab').classList.add('active');
    document.getElementById('loginTab').classList.remove('inactive');
    document.getElementById('signupTab').classList.add('inactive');
    document.getElementById('signupTab').classList.remove('active');
  }

  function showSignup() {
    document.getElementById('loginForm').style.display = 'none';
    document.getElementById('signupForm').style.display = 'block';
    document.getElementById('loginTab').classList.add('inactive');
    document.getElementById('loginTab').classList.remove('active');
    document.getElementById('signupTab').classList.add('active');
    document.getElementById('signupTab').classList.remove('inactive');
  }
</script>
{% endblock %}

backend/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Shlaiman Finder{% endblock %}</title>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='dark-mode.css') }}" id="dark-mode-stylesheet" disabled>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">
    
    <!-- Open Graph Meta Tags -->
    <meta property="og:title" content="Shlaiman Finder">
    <meta property="og:description" content="Find your Shlaiman friend and enjoy shows together with Shlaiman Finder.">
    <meta property="og:image" content="https://shlaiman.online/static/images/preview.png">
    <meta property="og:image:secure_url" content="https://shlaiman.online/static/images/preview.png">
    <meta property="og:url" content="https://shlaiman.online">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Shlaiman Finder">
    <meta property="og:image:width" content="310">
    <meta property="og:image:height" content="350">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Shlaiman Finder">
    <meta name="twitter:description" content="Find your Shlaiman friend and enjoy shows together with Shlaiman Finder.">
    <meta name="twitter:image" content="https://shlaiman.online/static/images/preview.png">
    <meta name="twitter:image:width" content="310">
    <meta name="twitter:image:height" content="350">

    <!-- PWA Configuration -->
    <meta name="theme-color" content="#FF5722">
    <link rel="apple-touch-icon" href="{{ url_for('static', filename='images/android-chrome-192x192.png') }}">

    <meta name="user-id" content="{{ current_user.id }}">
    
    {% block head %}{% endblock %}
    
    <style>
        body {
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center;
            /* background-blend-mode: normal; */
        }
    </style>
</head>
<body>
    <nav>
        <ul>
            {% if current_user.is_authenticated %}
                <button class="nav-button" data-page="index"><a href="{{ url_for('general_bp.home') }}">Home</a></button>
                <button class="nav-button" data-page="profile"><a href="{{ url_for('profile_bp.profile') }}">Profile</a></button>
                {% if current_user.is_authenticated and current_user.superuser %}
                    <button class="nav-button" data-page="superuser"><a href="{{ url_for('superuser_bp.superuser_view') }}">Superuser</a></button>
                    <button class="nav-button" data-page="test-location"><a href="{{ url_for('location_bp.test_location') }}">Test Location</a></button>
                {% endif %}
                <button class="nav-button" data-page="map_view"><a href="{{ url_for('general_bp.map_view') }}">Maps</a></button>
                <button class="nav-button" data-page="shows"><a href="{{ url_for('show_bp.shows') }}">Shows</a></button>
                <button class="nav-button" data-page="my_shows"><a href="{{ url_for('show_bp.my_shows') }}">My Shows</a></button>
                <button class="nav-button" data-page="friends"><a href="{{ url_for('general_bp.friends') }}">Friends in Group</a></button>
                <button class="nav-button" data-page="soundboard"><a href="{{ url_for('soundboard_bp.sounds_page') }}">Sound Board</a></button>
                <!-- <button class="nav-button" data-page="join_group"><a href="{{ url_for('general_bp.join_group') }}">Join Group</a></button> -->
                <button class="nav-button" data-page="sos"><a href="{{ url_for('sos_bp.sos_page') }}">SOS</a></button>
                <button id="dark-mode-toggle">Toggle Dark Mode</button>
                <button class="nav-button" id="logout-btn"><a href="{{ url_for('auth_bp.logout') }}">Logout</a></button>
                <script src="{{ url_for('static', filename='dark-mode.js') }}"></script>
            {% endif %}
        </ul>
    </nav>
    <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul class="flashes">
                    {% for category, message in messages %}
                        <li class="{{ category }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var images = [
                "{{ url_for('static', filename='images/background.png') }}",
                "{{ url_for('static', filename='images/background2.png') }}",
                "{{ url_for('static', filename='images/background3.png') }}",
                "{{ url_for('static', filename='images/background4.png') }}"
            ];
            var randomImage = images[Math.floor(Math.random() * images.length)];
            document.body.style.backgroundImage = 'url(' + randomImage + ')';
        });
    
        async function registerWorker() {
            console.log('Attempting to register service worker...');

            if ('serviceWorker' in navigator) {
                try {
                    console.log('Service worker is supported in this browser.');
                    const options = { scope: '/' };
                    const registration = await navigator.serviceWorker.register('/service-worker.js', options);

                    console.log('ServiceWorker registration attempt finished.');
                    console.log('ServiceWorker registration successful with scope: ', registration.scope);

                    registration.onupdatefound = () => {
                        const installingWorker = registration.installing;
                        installingWorker.onstatechange = () => {
                            if (installingWorker.state === 'installed') {
                                if (navigator.serviceWorker.controller) {
                                    // New update available
                                    if (confirm('New update available. Do you want to update?')) {
                                        window.location.reload();
                                    }
                                }
                            }
                        };
                    };

                    window.dispatchEvent(new Event('sw-toggle'));
                } catch (e) {
                    console.error('ServiceWorker registration failed:', e);
                    console.log('Error name:', e.name);
                    console.log('Error message:', e.message);
                    console.log('Error stack:', e.stack);
                }
            } else {
                console.log('Service Worker is not supported in this browser.');
            }
        }

        window.addEventListener('load', registerWorker);

        function isOnline() {
            return navigator.onLine;
        }

        function showOfflineAlert() {
            alert('No active internet connection. Please connect to the internet.');
        }

        window.addEventListener('online', function() {
            console.log('Back online');
            // Optionally refresh data here
        });

        window.addEventListener('offline', function() {
            alert('You have lost internet connection. Some features may not be available.');
        });
    </script>
</body>
</html>

backend/app/templates/edit_user.html
{% extends "base.html" %}

{% block title %}ShlaimanFinder - Edit User{% endblock %}

{% block content %}
<h1>Edit User</h1>
<form id="editUserForm">
    <label for="email">Email:</label>
    <input type="email" name="email" id="email" value="{{ user.email }}" required>
    <br>
    <label for="password">Password (leave blank to keep current password):</label>
    <input type="password" name="password" id="password">
    <br>
    <label for="group">Group:</label>
    <select name="group_id" id="group">
        <option value="">No Group</option>
        {% for group in groups %}
            <option value="{{ group.id }}" {% if user.group_id == group.id %}selected{% endif %}>{{ group.name }}</option>
        {% endfor %}
    </select>
    <br>
    <button type="submit">Save Changes</button>
</form>
<a href="{{ url_for('superuser_bp.superuser_view') }}">Cancel</a>

<script>
document.getElementById('editUserForm').addEventListener('submit', function(event) {
    event.preventDefault(); // Prevent default form submission

    const userId = {{ user.id }};
    const formData = new FormData(event.target);
    const data = Object.fromEntries(formData.entries());

    fetch(`/superuser/edit/${userId}`, {
        method: 'PUT',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(data)
    })
    .then(response => {
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        return response.json();
    })
    .then(data => {
        console.log('User updated:', data);
        window.location.href = "{{ url_for('superuser_bp.superuser_view') }}"; // Redirect to superuser view
    })
    .catch(error => {
        console.error('Error updating user:', error);
    });
});
</script>
{% endblock %}

backend/app/templates/friends.html
{% extends "base.html" %}

{% block title %}ShlaimanFinder - Friends{% endblock %}

{% block content %}
<h1>Friends in Your Group</h1>
<div id="friends-list" class="friends-container">
    <p id="no-friends-message" style="display:none;">No friends in current group - Join a group to view friends.</p>
</div>

<div id="location-info">
    <h2>User Location</h2>
    <p id="location-details"></p>
</div>

<script src="{{ url_for('static', filename='storage.js') }}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Fetch friends' locations and handle caching
        fetchFriendsLocations();
    });

    function showOfflineAlert() {
        alert('No active internet connection. Please connect to the internet.');
    }

    function isOnline() {
        return navigator.onLine;
    }
</script>
{% endblock %}